version: '3.9'

services:
  db:
    image: postgres:16
    container_name: fitflex-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: fitflex
      POSTGRES_PASSWORD: fitflex
      POSTGRES_DB: fitflex
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
